dist: trusty

# INSTALL MONGO

services:
  - mongodb

before_install:
  - curl https://glide.sh/get | sh

# INSTALL GO

language: go

go:
  - 1.8
  - master

install:
  - glide install

script:
  # DRIVERS
  - go test ./drivers/database -v -cover
